### ISSUE TITLE
Documentation should mention that non-IVM runtime is not supported

### ISSUE THREAD

**Issue by daboross** [rustyscreeps/screeps-game-api#136]
See https://github.com/daboross/screeps-in-rust-via-wasm/pull/135#issuecomment-467716802.

We just need to stick this somewhere visible - not sure where, but don't want to forget this.

**Comment by shanemadden** [comment]
Per o4 in discord on 10/17, "legacy VM is gone forever" -- since the shared VM is no longer an option, this documentation is no longer needed/relevant.
