### ISSUE TITLE
Attackable structures don't always have hits early-game

### ISSUE THREAD

**Issue by Discookie** [rustyscreeps/screeps-game-api#139]
For example, in tutorial 5, all of the extensions have `undefined` hits and `undefined` hitsMax.  
The Novice area's borders are Constructed walls but they don't have any hits either, because they are decaying.

Currently the API panics if I call `.hits()` on either of those things:
```
Panic error message: js_unwrap at 381 in {...}\screeps-game-api\src\objects\mod.rs: TypeMismatch { expected: "Number which fits into u32", actual: "undefined" }
```

I think these are the only 2 objects I've seen this happen with, but I'm not sure if there's any reasonable edge-case detection, other than appending a blanket `|| 0` for these 2 objects.

**Comment by daboross** [comment]
Thanks for finding this!

This is an interesting issue, which I hadn't considered. We definitely want to fix this for novice area borders, at least.

With the extensions in tutorial 5, this seems like it could be the game's fault for being inconsistent. I'm fine with a blanket fix fixing that as well, but if we can get the game to fix that issue that'd be great too.
