### ISSUE TITLE
Room.create_flag and RoomPosition.create_flag error on flag name return

### ISSUE THREAD

**Issue by tyler-conrad** [rustyscreeps/screeps-game-api#155]
The return type for create_flag is ReturnCode but the javascript function for creating a flag returns a string that is is flag name whenever a new flag is created.  This causes the following error:

`expected Flag.createFlag to return ReturnCode: TypeMismatch { expected: "Number which fits into i32", actual: "String" }`

**Comment by daboross** [comment]
Thanks for finding this!

I'd forgotten that flags return names on success, definitely want to fix that. They can still return a code on failure, so we'll probably need some more complicated return type, but that can be worked out.

**Comment by daboross** [comment]
Should be fixed in git version as of https://github.com/daboross/screeps-in-rust-via-wasm/pull/157.

**Comment by daboross** [comment]
Fixed in screeps-game-api 0.5.0!
