### ISSUE TITLE
Implement changes from the power creep era update

### ISSUE THREAD

**Issue by ASalvail** [rustyscreeps/screeps-game-api#158]
Here is the changelog:
https://blog.screeps.com/2019/03/power-era/

- [ ] Interface to `PowerCreep`
- [ ] Interface to `Game.powerCreeps` and `Game.gpl`
- [ ] Add `RoomObject.effects`
- [ ] Add `StructureController.isPowerEnabled`
- [x] Add interface to `RawMemory.interShardSegment`
- [x] We might have to deal with `RoomPosition` not returning strings anymore (see changelog)

**Comment by daboross** [comment]
I think our code should be robust for the `RoomPosition` changes, but it might be worth it to take advantage of the new representation for faster translation speeds if we want to do that.

**Comment by daboross** [comment]
I've done an initial update of the constants related to power creeps in #164, but added no real power creep functionality.

I think #163 should work for the inter-shard memory. Do you think we should add an interface to the deprecated `interShardSegment` too?

**Comment by ASalvail** [comment]
> I think #163 should work for the inter-shard memory. Do you think we should add an interface to the deprecated `interShardSegment` too?

Don't see the point. Clearly, this won't break any rust code!
