### ISSUE TITLE
Update the contributing.md

### ISSUE THREAD

**Issue by ASalvail** [rustyscreeps/screeps-game-api#177]
Some advice there are not up to date with the new rust edition or how we've been formatting code lately. It should be updated to reflect that.

I would move to require a changelog line in the unreleased section for every PR (unless it's a small fix). 

Finally, I'd remove a lot of the nitty-gritty details and require people to run `rustfmt` prior to a PR getting merged (travis could check for clippy and rustfmt?) which should simplify the requirements.

**Comment by daboross** [comment]
I'd like to keep in the thing about import ordering, since rustfmt won't fix that - but getting rid of the rest sounds good to me. Glad we have auto-grouping imports now.
