### ISSUE TITLE
Split repository into two repositories (under shared organization, maybe?)

### ISSUE THREAD

**Issue by daboross** [rustyscreeps/screeps-game-api#181]
Not sure if this needs to happen _now_, but it's something on the radar.

`cargo-screeps` and `screeps-game-api` are related, and work well together, but aren't fundamentally dependent on each other to function. I originally put them into the same repository because they were fairly small projects, and worked towards a common goal. But they've gotten bigger, and with more people using both they could probably use some more room. Splitting them, and possibly moving both under a new github organization, could be a good idea in the future.

There are other advantages to splitting them too, like not having to build both for pull requests which only really effect.

Biggest disadvantage I see is loosing the github issues which are shared on this repository. We could mitigate this by renaming `screeps-in-rust-via-wasm` to `screeps-game-api`, but then we'd still loose issues associated with `cargo-screeps`.

**Comment by snorrwe** [comment]
I agree about splitting them now, but please do not ever apologize for something like this. You do not have to convince us that this is a good idea.

> We could mitigate this by renaming screeps-in-rust-via-wasm to screeps-game-api, but then we'd still loose issues associated with cargo-screeps.

Should this happen it's a perfectly valid to dismiss as not this repo's [screeps api] problem

**Comment by daboross** [comment]
Just trying to lay out some of the reasoning here, mostly. I mean we are still (currently) the central repo for both `screeps-game-api` and `cargo-screeps`, even if we may not be when this is resolved?
