### ISSUE TITLE
Use 32bit representation for room names and room positions

### ISSUE THREAD

**Issue by daboross** [rustyscreeps/screeps-game-api#191]
Ever since https://github.com/screeps/engine/pull/87, screeps has internally represented RoomPositions as 32 bit integers.

It isn't strictly guaranteed that the world is small enough to do this, but it's as close to a guarantee as we'll get. I think it should be reasonable to represent `LocalRoomPosition`s locally as the same 32 bit integer, and we should be able to switch `LocalRoomName` to use that representation as well (maybe exactly the same, with 0,0 room coord so we can easily add room name to room coordinates).

If we do this, then it'd probably be reasonable to use `LocalRoomName` and `LocalRoomPosition` in more places. Converting `RoomPosition` to `LocalRoomPosition` would become a single integer copy, so we could probably use `LocalRoomPosition` for everything except sending positions into methods that require the `RoomPosition` prototype, like `Creep::move_to`.

**Comment by ASalvail** [comment]
Honestly, with a world that has 256x256 rooms, the tick speed would be so slow that I think it's safe to assume it'll never be reached. However, wouldn't it be simpler to put that integer in `RoomPosition` itself? Or maybe implement `Deref<RoomPosition> for LocalRoomPosition`?

**Comment by daboross** [comment]
I think it can be useful to have the two representations, even if just for the sake of having `#[derive(ReferenceType)]` make the right conversion code for `RoomPosition`. We can't use `#[derive(ReferenceType)]` on something which doesn't actually store a reference to JS, and if it stores a reference to JS it will be more expensive to move around.

I mean, here are some differences we could only keep if we have separate types:

- `RoomPosition` can be `AsRef<Reference>` due to storing a reference internally
- when converting to JS, `RoomPosition` is already a structure with a prototype
- `RoomPosition` gets very nice implementations of all the conversion types because of `#[derive(ReferenceType)]`
- `RoomPosition` deserializes from JavaScript if and only if the JS side is a `RoomPosition` (side effect of `#[derive(ReferenceType)]`)
- `RoomPosition` can allow using the 'pos' property from an object as an argument to another method without ever needing to create a `new RoomPosition`.
- `LocalRoomPosition` can be `Copy` because it doesn't store a reference
- `LocalRoomPosition` can have cheap addition because it has a local number
- `LocalRoomPosition` can deserialize from any object with `x`,`y` and `roomName` properties

These different use cases are possible because the internal representations are different.

We could possibly switch the names, making them `RoomPosition` and `RemoteRoomPosition`, which could make it nicer.

Or, I mean, we could get rid of the remote variant altogether and just make  `LocalRoomPosition` serialize to JavaScript using something like `new RoomPosition();`. It might make something like `creep.move_to(&source.pos());` slightly slower as we'd have to create a new position, but maybe that's a negligible cost?

**Comment by daboross** [comment]
Having just one `RoomPosition` struct which wraps a `u32` would make it all much simpler, though...

It could be worth the cost of having to do `new RoomPosition` (or `Object.setProtoTypeOf()` - we might need to if `RoomPosition` doesn't accept that 32bit integer as a parameter) even when we send room positions we just got from JS back to JS.

**Comment by ASalvail** [comment]
There is something to be said about simplicity. `LocalRoomPosition` seems to trip people up. 

The overhead of building new `RoomPosition` seems trivial in the grand scheme of things. Plus, we should be able to set `.__packedPos` manually.

**Comment by daboross** [comment]
True! Simplicity has value.

I'm all for setting `__packedPos`, but I think setting the prototype to `RoomPosition` might be more expensive than that. Eh, testing required I guess.

**Comment by ASalvail** [comment]
Premature optimization?
For now: simplicity > optimization, we can see if it's a problem later (it probably won't be?)
Once dozen of people use the codebase and we actually have performance data, then it's another story 😛
