### ISSUE TITLE
Fields on Bodypart should be marked as pub

### ISSUE THREAD

**Issue by Kyle-B** [rustyscreeps/screeps-game-api#214]
Currently Bodypart is defined as:

```rust
#[derive(Clone, Debug)]
pub struct Bodypart {
    boost: Option<ResourceType>,
    part: Part,
    hits: u32,
}
```

Which prevents access to any of the fields. These should be marked as public so this struct can be used.

**Comment by daboross** [comment]
Sounds like a reasonable change to me!
