### ISSUE TITLE
Rename `Structure` to `StructureEnum` (or similar), and remove it as a first-class citizen

### ISSUE THREAD

**Issue by daboross** [rustyscreeps/screeps-game-api#227]
`Structure` stands out as the one "object" type which isn't a direct reference wrapper, and in general isn't at all consistent with other wrapper types.

While it is useful, I don't think it deserves it's place as the "default" type for representing a `Structure`.

What would you think of replacing `Structure` with a plain reference-wrapper (similar to `RoomObject`), and relegating the current thing named `Structure` to the side?

We could still make it reasonably nice to use by implementing `From<Structure>` for `StructureEnum`, and vice-versa.

One thing I think this could open up is implementing a few alternative `StructureEnum`-like things. Plain reference types deserve to exist because they're the simplest kind of structure, but I don't think there's a similar obvious reason that `Structure` being implemented as an enum is the best. If the default wasn't a "nice extension", but rather just the simplest thing, that would make it easier to experiment with other designs (in-crate or out-of-crate).

Other ideas could be like:
- a whole set of enums, matching like `TransferableThing`, `WithdrawableThing`, `HasStorageThing`, etc. with fallible conversions inbetween
- a reference-wrapper `SomeStructure` which implements all possible structure operations (type, my, etc.) and fails at runtime if the structure doesn't implement them
- two wrapper around `Box<dyn StructureProperties>` and `&dyn StructureProperties` which allow casting to different `dyn X` things by checking the type at runtime
- something like `struct StructurePhantom<T: ?Sized>(Reference, PhantomData<T>)` which could be typed to `dyn StructureProperties`, or `dyn Withdrawable`, etc.

I've got no idea how pheasible all of these would be, or if any would provide concrete advantages over our current `Structure`. But I think if the current "smart" solution was no longer a default but rather an add-on, it would be easier to add in other "smart" solutions as similar add-ons.

cc @ASalvail, @Dessix

**Comment by Dessix** [comment]
A definite yes from me. Working with structure types is currently the most painful part of the API in my opinion.

**Comment by ASalvail** [comment]
Not saying _no_, but how about we start from actual examples of code we would like to use? If we gather some such examples, it'd give us a better idea of what/how we would like to implement.

@Dessix what is annoying you with the structures? I'm catching up, but I'm much further code-wise.

**Comment by daboross** [comment]
> Not saying no, but how about we start from actual examples of code we would like to use? If we gather some such examples, it'd give us a better idea of what/how we would like to implement.

I think this is definitely a good idea. I should... use `Structure` more.

My main gripe with the current `Structure` implementation is just that it's kind of arbitrary that it's implemented as an enum, and that no other similar types are implemented that way - they're all plain reference wrappers.

**Comment by ASalvail** [comment]
There is the option of removing them entirely and expect people to use `dyn StructureProperties`. I always prefer to remove code rather than add more. 😛 

I'd rather we solve a concrete problem when adding to the API elements that aren't strictly necessary.

**Comment by daboross** [comment]
I'm in favor of removing code - but not necessarily functionality? Like this _can be useful_, but I don't think it's a sane default. Maybe it could move to a separate repo?

With `dyn StructureProperties`, I like it in principle - but I think it'd be much more code than a reference wrapper in practice.

I mean the two places `Structure` is actually used is as a result from `find::STRUCTURES` and `look::STRUCTURES`, and it'd be super easy to switch those over to a reference wrapper. To get a `dyn StructureProperties`, though, we'd need code like what our current `Structure` enum does - where it first gets the type manually, then switches on that an

**Comment by ASalvail** [comment]
Oh, sure the reference wrapper makes sense. Actually, it's probably the easiest and most useful short-term.
