### ISSUE TITLE
ObjectId encoding subtly wrong for LokIJS-backed private servers

### ISSUE THREAD

**Issue by daboross** [rustyscreeps/screeps-game-api#244]
Turns out object IDs generated by LokIS have the possibility of starting with a `'0'`, and our current ObjectId implementation doesn't store this information. `"0df4aea318bd552"`, for instance, will be parsed fine, but we'll reproduce it as `"df4aea318bd552"` which the server won't recognize.

When doing research for ObjectId, I found a [`generateId` function that was part of the engine's _mock code_], and skipped over the [actual idGen function](https://github.com/screeps/storage/blob/2037ec3db916b947dd5df24986313ce518f9b913/lib/db.js#L106-L117) used.

Some ideas (from myself and mostly Dessix) for solving this:

- always zero-pad output to 15 digits
- store a length or number of 0 bits in the data
- config variable to enable padding, used when deploying to LokiJS servers
- if resolving a non-zero-padded ID fails, try with padding.
  
  if that succeeds, set a global variable and pad all IDs in the future

Storing a length would probably be the most reliable solution, but it also imposes an extra cost for storing length, and that cost will never be necessary on MongoDB-backed servers. Always zero-padding to 15 digits would work, but wouldn't be very future-proof for different ID generation strategies (or for 505 years in the future, when the id gen mechanism will rotate over and start producing 16-digit IDs).

A config variable is viable, but has the same problems as zero-padding IDs, and it introduces a UX cost - users would have to do something extra to deploy to private servers.

The last option seems a bit costly at first, but since it should only ever be used in private servers running LokiJS, maybe that cost is alright? I think most people who are either measuring CPU usage or wanting the fastest could should already be running MongoDB private servers.

**Comment by ASalvail** [comment]
Zero-padding the string when it's sent over to JS seems like the easiest solution and adds the least overhead. I must say I am not swayed by the argument about anything that happens later than 5 years in the future 😂

**Comment by daboross** [comment]
That would be the easiest solution! :p

I'm still a bit afraid of baking things like this, but I guess it's unlikely that they'll change the format, even for private servers. If we do the "always zero-pad to 15 digits" option, it would break 505 years in the future, but also if any private server ever switches to IDs with fewer than 15 digits, which I might be more worried about?

**Comment by ASalvail** [comment]
We'll address this when it happens.

Adam Salvail
