### ISSUE TITLE
Creep::body fails when parts aren't boosted

### ISSUE THREAD

**Issue by daboross** [rustyscreeps/screeps-game-api#245]
This line:

```rust
            let boost_v =
                js!(return __resource_type_str_to_num(@{self.as_ref()}.body[@{i}].boost););
```

Will throw an error, since `__resource_type_str_to_num` always requires valid input.

**Comment by Dessix** [comment]
I fixed this locally with:
`js!(const b=@{self.as_ref()}.body[@{i}].boost||null; return b && __resource_type_str_to_num(b););`

**Comment by ASalvail** [comment]
... you know you're allowed to open PRs, right? :P
