### ISSUE TITLE
Make MemoryReference::get generic wrt Error

### ISSUE THREAD

**Issue by j-browne** [rustyscreeps/screeps-game-api#271]
I was reminded by @internetimagery of a fix I made a while ago: 17d45721e44d9429fa13325f43056a5e5503ff3e
My memory is a bit hazy, since it was so long ago, and I forget why I held off on submitting it. If I remember correctly, it was to fix problems with implementing `Serialize` and `Deserialize`. If this is desired, should other parts also be changed in the same way, i.e. `get_path`?

**Comment by internetimagery** [comment]
Thanks @j-browne! :)

Yeah I hit this issue as well when trying to serialize a standard struct / enum. eg

```rust
use serde::{Serialize, Deserialize};
use stdweb::{__js_serializable_boilerplate, js_serializable, js_deserializable};
use screeps::Creep;

#[derive(Serialize, Deserialize)]
enum Hello {
    World,
}
js_serializable!(Hello);
js_deserializable!(Hello);

fn test(creep: &Creep) {
    let var = creep.memory().get::<Hello>("World");
}
```

```
...
= note: expected type `stdweb::ecosystem::serde::ConversionError`
              found type `stdweb::webcore::value::ConversionError`
```
