### ISSUE TITLE
Use `Result<(), ??>` over `ReturnCode`

### ISSUE THREAD

**Issue by daboross** [rustyscreeps/screeps-game-api#3]
Making an issue here as a reminder.

It seems generally be more "rusty" to do this. The one disadvantage is having a two-byte return type size rather than one-byte, but that shouldn't be too large of a problem at all. We could even leave `ReturnCode` as a type alias for `Result<(), ??>`.

One question I'm not sure about is what to call the error portion. I'm thinking `ErrorCode` would work well, but just `Error` or `GameError` might also be good. I'm partially against `Screeps*` names because of duplication with `screeps::` crate name.

**Comment by ASalvail** [comment]
With return code built as enums, this becomes obsolete. Instead of having a two element enum (`Ok` or `Err`) we have a ~20 elements enum.

I'd move to close this. @daboross

**Comment by daboross** [comment]
@ASalvail IIRC this has always been the case, there was never a time that `ReturnCode` wasn't a 20-element enum

The main advantages of `Result` that I was thinking of here are more from it being Result than from it being an enum in general. Like:

- being able to use the `?` operator to propogate
- having combinator functions, like `res.and_then(|()| second_action())`
- integration with other error types - with this you could `impl From<ErrorCode> for YourError` and then use, for instance, `move_to()?` in a function returning `Result<_, YourError>`
- making it even clearer that everything except 'Ok' is an error, given that the pattern of returning `Result` is used universally
