### ISSUE TITLE
Use Auth token instead of plain text password?

### ISSUE THREAD

**Issue by PapaOscar90** [rustyscreeps/screeps-game-api#335]
Would it be possible to use the Auth token instead?

Could limit damage to my account.

**Comment by alelazar** [comment]
Where is it making you use your password? Auth token should work. 

In general, auth tokens can go anywhere a password can.

**Comment by shanemadden** [comment]
See the documentation on cargo-screeps [here](https://github.com/rustyscreeps/cargo-screeps/blob/master/README.md) - if you remove the username/password from your `screeps.toml` and set `auth_token = "your-token-here"` instead, you should be good to go!

**Comment by PapaOscar90** [comment]
💯
