### ISSUE TITLE
Remove merged and stale branches

### ISSUE THREAD

**Issue by Domkeykong** [rustyscreeps/screeps-game-api#370]
Remove merged and stale branches for cleanup and to also not confuse people which branch they should download and use.

Merged branches are:
These don't have any purpose for existing
- [fix-245](https://github.com/rustyscreeps/screeps-game-api/tree/fix-245) Merged in #247
- [hack-244-loki-id-resolution](https://github.com/rustyscreeps/screeps-game-api/tree/hack-244-loki-id-resolution) merged in #248 

Stale Branches:
Either remove them, merge them or create a tag if they are still important.
- [struct_ref](https://github.com/rustyscreeps/screeps-game-api/tree/struct_ref) last updated 14-07-2019
- [improve-js_unwrap-errors](https://github.com/rustyscreeps/screeps-game-api/tree/improve-js_unwrap-errors) last updated 22-07-2019
- [small-doc-additions](https://github.com/rustyscreeps/screeps-game-api/tree/small-doc-additions) last updated 28-08-2019
- [reformat](https://github.com/rustyscreeps/screeps-game-api/tree/reformat) last updated 17-10-2019

**Comment by shanemadden** [comment]
Cleaned up, thanks!
