### ISSUE TITLE
`hits`/`hitsMax` are either `0` or `undefined` on controllers

### ISSUE THREAD

**Issue by shanemadden** [rustyscreeps/screeps-game-api#458]
See also #457 - `my` is undefined in some of the same cases.

`hits` and `hitsMax` attributes are variably `undefined` and `0` in js responses from the game engine; based on investigation from asquared31415 in discord, controllers which have been unclaimed due to respawn will have zeroes but other controllers will have this attribute undefined: https://github.com/screeps/backend-local/blob/7520c8c7e6a443ad955d25e064dbd151a909d8cb/lib/utils.js#L151-L164

Instead of going to an `Option<u32>`  for `hits`/`hitsMax` in the public API, we should likely coalesce the `None` variant to `0`, to make the API returns consistent with the documentation - the zeroes from unclaimed rooms will always be there, so we should make that the variant to be expected for controllers (as well as other invulnerable structures less complicated than the edge cases apparently present in controllers!)

**Comment by asquared31415** [comment]
(note that a lot of the other controller properties are not properly initialized or may become unset on respawn too, they all need additional work)

**Comment by shanemadden** [comment]
Copying from discord: upgrade_blocked, ticks_to_downgrade, safe_mode_available, progress, progress_total, and is_power_enabled maybe/probably need to handle an undefined case and potentially should coalesce to `0` or `false`

**Comment by asquared31415** [comment]
I recently sent a bug report because I mentioned this in passing and o4 asked me to send a report, which I had forgotten to do.  This fallback might be useful, but I expect that at some point this bug may be fixed.
