### ISSUE TITLE
What kind of RoomVisual support do we want?

### ISSUE THREAD

**Issue by daboross** [rustyscreeps/screeps-game-api#46]
Opening this as a separate issue from #30 since there are multiple ways we could support this and discussing it seems fairly self contained.

`RoomVisual` allows drawing nice graphics on rooms. It's a convenient API. However, all of the JS code in `RoomVisual` does is create the right JSON structures then call `console.addVisual(room_name, structure)`.

In implementing bindings for `RoomVisual`, we could either wrap `RoomVisual`'s methods themselves, or just wrap `console.addVisual` and create a `RoomVisual` equivalent ourselves in pure rust code.

**Comment by ASalvail** [comment]
The latter seems to make more sense. It'd greatly reduce the overhead of communicating through the screeps API.

I'm curious however: would we bypass [this restriction](https://docs.screeps.com/api/#RoomVisual)
> However, there is a usage limit: you cannot post more than 500 KB of serialized data per one room (see getSize method).

**Comment by daboross** [comment]
I don't believe we would - the check is done in `addVisual` itself rather than in any of the wrapper methods: https://github.com/screeps/engine/blob/551aa41163c45273d706ce238c6b35f379c0149e/src/game/console.js#L40

**Comment by Azaril** [comment]
Here's a PR for the full API: https://github.com/rustyscreeps/screeps-game-api/pull/306

**Comment by Azaril** [comment]
Closing as resolved with https://github.com/rustyscreeps/screeps-game-api/pull/306
