### ISSUE TITLE
screeps::constants::Direction does not implement JsCollectionIntoValue

### ISSUE THREAD

**Issue by jhelwig** [rustyscreeps/screeps-game-api#464]
`screeps::game::map::describe_exits` returns a `JsHashMap<Direction, RoomName>`, but `Direction` does not implement `JsCollectionIntoValue`, which is a required trait for the key passed to `JsHashMap::get`. Not having the trait implemented makes it a bit more difficult to retrieve a specific direction's room name.

**Comment by shanemadden** [comment]
Big whoops on the oversight, thanks for letting us know!

**Comment by jhelwig** [comment]
Thanks for fixing this!
