### ISSUE TITLE
JsMap / JsVec

### ISSUE THREAD

**Issue by daboross** [rustyscreeps/screeps-game-api#47]
These two structures could be `Reference` wrappers with types, like:

```rust
struct JsMap<K, V> {
    inner: Reference,
    phantom: PhantomData<HashMap<K, V>>,
}
struct JsVec<T> {
    inner: Reference,
    phantom: PhantomData<Vec<T>>,
}
```

They would provide access to typed getters and setters for JavaScript objects and arrays without loading the whole object/array into memory. They would be useful primarily for simple objects whose keys we don't know at compile time and for large arrays.

They would have implementations for `Into<HashMap<K, V>>`/`Into<Vec<T>>` and `.local()` methods for conveniently turning them into those if one wants to use an API and does  want a local version. We'd also add a `IntoRemote` trait to provide `.remote()` methods on `Vec<T>` and `HashMap<K, V>` to turn them into `JsVec<T>` and `JsMap<K, V>` respectively.

I imagine at minimum the following API bindings will want to be rewritten to use these structures once we have them:

`JsMap`:

- `.store` property on `HasStore` things
- `Creep.carry`
- `Game.*` objects (`construction_sites`, `creeps`, `flags`, `rooms`, `spawns`, `structures`)
- `RawMemory.segments`

`JsVec`:

- `Creep.body`
- `PathFinder.search` return

**Comment by ASalvail** [comment]
A few questions:
- Do you check whether the `Reference` actually matches those types (`Array`/`Object`) when creating the object or when accessing the attributes? Or maybe it is a `ReferenceType` that does neither?
- When would we prefer direct serialization over a `JsMap`?
- How do you expect to type `JsMap`? I guess they will always be `JsMap<String, V>`?
- In the same vein as the previous question, what should be the default behaviour when `V` can have multiple types?
- Could there be any use for a `.remote()` method that would be the opposite of `.local()`

In any case, it seems easy enough to implement and could make the code cleaner in several places. +1

**Comment by daboross** [comment]
> Do you check whether the `Reference` actually matches those types (`Array`/`Object`) when creating the object or when accessing the attributes? Or maybe it is a `ReferenceType` that does neither?

I'd like to check that arrays are arrays, but probably nothing for objects. Mostly because everything's an object? Things which aren't objects, like integers, etc. aren't References either so that check will probably manage it.

`IntoExpectedType` would ignore the array checks.

> When would we prefer direct serialization over a `JsMap`?

Whenever we know the keys. `JsMap` would only ever be usable for objects whose keys depend on runtime variables.

> How do you expect to type `JsMap`? I guess they will always be `JsMap<String, V>`?

Yeah, `JsMap<String, V>` or `JsMap<i32, V>`, etc. depending on the thing. For non-String types I would expect it to bring a string in from JS then use `FromStr` to convert it into whatever type it is.

> In the same vein as the previous question, what should be the default behaviour when `V` can have multiple types?

If we have a type which could represent all of them, use that. For instance, `Game.structures` should be `JsMap<String, Structure>`.

> Could there be any use for a `.remote()` method that would be the opposite of `.local()`

That sounds like a good idea.
