### ISSUE TITLE
Uniformity in the derive we use for enum and struct

### ISSUE THREAD

**Issue by ASalvail** [rustyscreeps/screeps-game-api#50]
For now, most enum/structs derive any subset of `Debug`, `Clone`, `Copy`, `PartialEq`, `Eq`, `Hash`, `Serialize`, `Deserialize`, `PartialOrd`, `Ord`, `Display`

What's the plan? Add stuff as it becomes useful? If so, should we have a basic set that we'd like to implement off the bat for our users?

**Comment by daboross** [comment]
My opinion on this:

I would expect us to have `Clone` and `Debug` as a minimum on everything.

For plain data, `Hash`, `PartialEq`, `Eq`, `PartialOrd`, `Ord` make sense. If it has all copyable data and we don't for see it not having copyable data, `Copy` would also be good.

With `Display`, I think it only makes sense for things that really have a useful user-oriented formatting. It should be on errors, possible custom data types, but I don't expect it to be on much.

That's what I imagine each type should have, at least. I've tried to stick to this when writing code but I'm sot sure how well this repository does. Most of it's wrappers of things without good display representations, so I would only expect the majority to have `Clone`, `Debug`.

Does that give a possible picture?

**Comment by daboross** [comment]
How do you feel about the state of things now?

#164 brought in at least some uniformity, I think.

**Comment by ASalvail** [comment]
True! We can raise the issue later if we find it's still a problem. Thanks for bringing that up.
