### ISSUE TITLE
Creep.move_to* methods are missing the visualize_path_style option

### ISSUE THREAD

**Issue by ASalvail** [rustyscreeps/screeps-game-api#79]
Related to #46 

Implementation of the `visualize_path_style` optional argument has been postponed until a decision is made about room visuals.

**Comment by jhessin** [comment]
What decision needs to be made about room visuals?

**Comment by Azaril** [comment]
Here's a PR for the full API: https://github.com/rustyscreeps/screeps-game-api/pull/306

**Comment by ASalvail** [comment]
> What decision needs to be made about room visuals?

Mostly, how to represent it in rust. Given how long this has been open, Azaril's version, if it works (😛) will probably be the answer.

**Comment by Azaril** [comment]
Closing as resolved with https://github.com/rustyscreeps/screeps-game-api/pull/306
